In [71]:
import numpy as np
import pandas as pd
import lightgbm as lgb
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split, cross_val_score, RepeatedStratifiedKFold, RepeatedKFold
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

### LightGBM Ensemble for Classification

In [54]:
from sklearn.datasets import make_classification
X,y = make_classification(
    n_samples = 1000,
    n_features = 20,
    n_informative = 15,
    n_redundant = 5,
    random_state = 7
)
X.shape, y.shape

((1000, 20), (1000,))

In [57]:
y[:5]

array([1, 1, 1, 0, 0])

In [58]:
model = lgb.LGBMClassifier()
cv = RepeatedStratifiedKFold(
    n_splits = 10,
    n_repeats = 3,
    random_state = 1
)

In [59]:
n_scores = cross_val_score(
    model,
    X,
    y,
    cv = cv,
    n_jobs = -1,
    scoring = 'accuracy'
)

In [60]:
print(f"Accuracy Score: {np.mean(n_scores):.3f}")
print(f"Standard Deviation: {n_scores.std():.3f}")

Accuracy Score: 0.930
Standard Deviation: 0.027

In [62]:
model = lgb.LGBMClassifier()
model.fit(X,y)

[LightGBM] [Info] Number of positive: 499, number of negative: 501
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000469 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499000 -> initscore=-0.004000
[LightGBM] [Info] Start training from score -0.004000

LGBMClassifier()

In [63]:
row = [0.2929949,-4.21223056,-1.288332,-2.17849815,-0.64527665,2.58097719,0.28422388,-7.1827928,-1.91211104,2.73729512,0.81395695,3.96973717,-2.66939799,3.34692332,4.19791821,0.99990998,-0.30201875,-4.43170633,-2.82646737,0.44916808]
yhat = model.predict(np.array(row).reshape(1, -1))
print(f"Predicted Class: {yhat[0]}")

Predicted Class: 1

In [64]:
X[:5,:]

array([[ 2.92994904e-01, -4.21223056e+00, -1.28833200e+00,
        -2.17849815e+00, -6.45276650e-01,  2.58097719e+00,
         2.84223878e-01, -7.18279280e+00, -1.91211104e+00,
         2.73729512e+00,  8.13956945e-01,  3.96973717e+00,
        -2.66939799e+00,  3.34692332e+00,  4.19791821e+00,
         9.99909984e-01, -3.02018750e-01, -4.43170633e+00,
        -2.82646737e+00,  4.49168082e-01],
       [-6.83990068e-02,  5.51884147e+00,  1.12389773e+01,
        -5.03969992e+00, -2.08678427e+00,  2.14968460e+00,
         5.59734187e-01,  1.51137767e+01, -3.07183375e+00,
        -2.57458353e+00,  3.32457612e+00,  2.06754191e+00,
        -5.24925807e+00, -2.15449971e+00,  4.93109130e+00,
         1.29673535e+00, -3.18613337e+00, -3.08994781e+00,
         1.19029898e+00,  1.62025622e+00],
       [ 7.31616218e-01, -6.84686328e-01, -9.81741943e-01,
        -2.55246528e+00, -5.27030762e+00, -1.56149846e+00,
        -1.16926915e+00, -2.10408711e+00, -1.13113880e+00,
         4.65477500e+00, -2.78659559e+00, -2.03476089e+00,
         2.14965707e+00, -1.34153720e-01, -1.19823052e+00,
        -2.72060438e+00, -1.23961137e-01,  5.65429655e+00,
        -6.46598657e-01, -3.15652999e+00],
       [ 2.30910747e+00, -3.20547870e-01, -6.59166409e+00,
         1.07052519e+00, -4.41876908e+00,  1.13427414e+00,
         2.34081313e+00, -5.98342540e+00,  6.75917154e-01,
        -1.00787898e+00, -7.61441215e-01,  6.86629700e+00,
         1.44227042e+00,  1.76867817e+00,  5.17366079e+00,
        -1.07016356e+00, -2.44706376e+00, -1.10903841e+00,
        -2.99703534e+00,  1.99321194e+00],
       [-4.88406017e-01, -3.21306489e+00,  1.10080488e+00,
        -1.35622345e+00,  5.32508624e+00,  7.29179246e-01,
        -2.57039579e-01, -1.03528400e+00,  4.78012646e-01,
        -1.07638212e-02, -2.27408124e-01,  2.55145605e+00,
         9.51593805e-01, -2.91490986e+00, -2.18684301e+00,
        -1.08912858e+00,  1.40645396e+00,  3.08242385e+00,
         9.25834511e-01, -2.32636171e+00]])

In [65]:
y[:5]

array([1, 1, 1, 0, 0])

In [66]:
model.predict(np.array( [-4.88406017e-01, -3.21306489e+00,  1.10080488e+00,
        -1.35622345e+00,  5.32508624e+00,  7.29179246e-01,
        -2.57039579e-01, -1.03528400e+00,  4.78012646e-01,
        -1.07638212e-02, -2.27408124e-01,  2.55145605e+00,
         9.51593805e-01, -2.91490986e+00, -2.18684301e+00,
        -1.08912858e+00,  1.40645396e+00,  3.08242385e+00,
         9.25834511e-01, -2.32636171e+00]).reshape(1,-1))

array([0])

### LightGBM Ensemble for Regression

In [67]:
from sklearn.datasets import make_regression
X,y = make_regression(
    n_samples = 1000,
    n_features = 20,
    n_informative = 15,
    noise = 0.1,
    random_state = 7
  )
X.shape, y.shape

((1000, 20), (1000,))

In [69]:
y[:5]

array([  50.26884554,  215.40172406, -125.18568205,   59.0238201 ,
       -119.60589148])

In [70]:
model = lgb.LGBMRegressor()

In [72]:
cv = RepeatedKFold(
    n_splits = 10,
    n_repeats = 3,
    random_state = 1
)

n_scores = cross_val_score(
    model,
    X,
    y,
    cv = cv,
    n_jobs = -1,
    scoring = 'neg_mean_absolute_error',
    error_score = 'raise'
)

In [73]:
print(f"MAE: {np.mean(n_scores):.3f}")
print(f"Standard Deviation: {n_scores.std():.3f}")

MAE: -60.004
Standard Deviation: 2.887

In [74]:
model = lgb.LGBMRegressor()
model.fit(X,y)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000462 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 20
[LightGBM] [Info] Start training from score 3.477325

LGBMRegressor()

In [ ]:
row = [0.20543991,-0.97049844,-0.81403429,-0.23842689,-0.60704084,-0.48541492,0.53113006,2.01834338,-0.90745243,-1.85859731,-1.02334791,-0.6877744,0.60984819,-0.70630121,-1.29161497,1.32385441,1.42150747,1.26567231,2.56569098,-0.11154792]

In [75]:
yhat = model.predict(np.array(row).reshape(1,-1))
print(f"Predicted Value: {yhat[0]:.3f}")

Predicted Value: -142.264

In [76]:
X[:5,:]

array([[ 0.20543991, -0.97049844, -0.81403429, -0.23842689, -0.60704084,
        -0.48541492,  0.53113006,  2.01834338, -0.90745243, -1.85859731,
        -1.02334791, -0.6877744 ,  0.60984819, -0.70630121, -1.29161497,
         1.32385441,  1.42150747,  1.26567231,  2.56569098, -0.11154792],
       [-0.15673157, -0.29174391, -1.35320829,  1.01707967, -0.07234307,
         0.18329942,  0.80973426, -0.64673968,  0.95275926,  1.1296854 ,
         0.54305733,  1.01971931,  1.11541185, -0.38065267, -1.35733838,
         0.8732109 , -1.31086876,  1.0656072 ,  2.47014304, -1.27650497],
       [-0.02584282, -0.245296  , -1.51973704, -0.03648676,  0.20572611,
        -0.38812155, -0.11075665, -0.56170187,  1.06349041,  0.32073524,
        -0.54435628,  0.27891341, -0.31698867,  0.00828387,  0.01565164,
         0.72827211, -1.53931289, -1.86585106,  0.61223733, -0.51494948],
       [-0.29306566,  1.96938905, -1.66551323, -1.04866012,  0.6226501 ,
        -1.5033859 , -0.04469142,  1.02053295,  0.75784968, -1.43402658,
         0.94770165, -0.38714878,  1.74684592,  1.41423374, -0.67402167,
        -0.36416973, -0.1789394 ,  0.95719313,  0.99392505,  0.62056717],
       [-0.55166999,  0.76691442, -0.43563374, -0.55355606, -1.23311242,
        -0.10471967,  1.43439012,  0.34667548,  1.10163208,  0.37671189,
        -0.91057275, -0.21211626,  1.17107755, -1.29147366, -0.34797556,
         0.50579007, -2.23621456,  0.14511147,  0.85185158, -0.95253951]])

In [77]:
y[:5]

array([  50.26884554,  215.40172406, -125.18568205,   59.0238201 ,
       -119.60589148])

In [78]:
model.predict(np.array([-0.55166999,  0.76691442, -0.43563374, -0.55355606, -1.23311242,
        -0.10471967,  1.43439012,  0.34667548,  1.10163208,  0.37671189,
        -0.91057275, -0.21211626,  1.17107755, -1.29147366, -0.34797556,
         0.50579007, -2.23621456,  0.14511147,  0.85185158, -0.95253951]).reshape(1,-1))

array([-118.41508548])

Load Dataset

In [79]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
data

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [80]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
data = data[features + ['Survived']].dropna()

data

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0         3    male  22.0      1      0   7.2500        S         0
1         1  female  38.0      1      0  71.2833        C         1
2         3  female  26.0      0      0   7.9250        S         1
3         1  female  35.0      1      0  53.1000        S         1
4         3    male  35.0      0      0   8.0500        S         0
..      ...     ...   ...    ...    ...      ...      ...       ...
885       3  female  39.0      0      5  29.1250        Q         0
886       2    male  27.0      0      0  13.0000        S         0
887       1  female  19.0      0      0  30.0000        S         1
889       1    male  26.0      0      0  30.0000        C         1
890       3    male  32.0      0      0   7.7500        Q         0

[712 rows x 8 columns]

Label Encoding for Categorical Data

In [81]:
label_encoders = {}
for col in ['Sex', 'Embarked']:
  le = LabelEncoder()
  data[col] = le.fit_transform(data[col])
  label_encoders[col] = le

In [87]:
label_encoders

{'Sex': LabelEncoder(), 'Embarked': LabelEncoder()}

In [82]:
data.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0       3    1  22.0      1      0   7.2500         2         0
1       1    0  38.0      1      0  71.2833         0         1
2       3    0  26.0      0      0   7.9250         2         1
3       1    0  35.0      1      0  53.1000         2         1
4       3    1  35.0      0      0   8.0500         2         0

Spliting data

In [84]:
X = data.drop(columns = ['Survived'])
y = data.Survived
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [86]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((569, 7), (143, 7), (569,), (143,))

In [88]:
model = lgb.LGBMClassifier()

cv = RepeatedStratifiedKFold(
    n_splits = 10,
    n_repeats = 3,
    random_state = 1
)

In [89]:
n_scores = cross_val_score(
    model,
    X,
    y,
    cv = cv,
    scoring = 'accuracy',
    n_jobs = -1
)

In [90]:
print(f"Accuracy: {np.mean(n_scores):.3f}")
print(f"Standard Deviation: {n_scores.std()}")

Accuracy: 0.808
Standard Deviation: 0.04659978443186808

In [108]:
model = lgb.LGBMClassifier(
    n_estimators = 500,
    learning_rate = 0.05,
    max_depth = 8,
    num_leaves = 32,
    subsample = 0.8,
    colsample_bytree = 0.75,
    reg_alpha = 0.1,
    reg_lambda = 0.1,
    min_split_gain = 0.01,
    min_child_weight = 10,
    random_state = 42,
    n_jobs = -1

)

In [109]:
model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 225, number of negative: 344
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043775 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 184
[LightGBM] [Info] Number of data points in the train set: 569, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.395431 -> initscore=-0.424541
[LightGBM] [Info] Start training from score -0.424541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(colsample_bytree=0.75, learning_rate=0.05, max_depth=8,
               min_child_weight=10, min_split_gain=0.01, n_estimators=500,
               n_jobs=-1, num_leaves=32, random_state=42, reg_alpha=0.1,
               reg_lambda=0.1, subsample=0.8)

In [110]:
yhat = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, yhat):.3f}")

Accuracy: 0.825

In [111]:
X_test.head()

     Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
641       1    0  24.0      0      0   69.3000         0
496       1    0  54.0      1      0   78.2667         0
262       1    1  52.0      1      1   79.6500         2
311       1    0  18.0      2      2  262.3750         0
551       2    1  27.0      0      0   26.0000         2

In [112]:
y_test.head()

641    1
496    1
262    0
311    1
551    0
Name: Survived, dtype: int64

In [113]:
model.predict(np.array([1,	1,	52.0,	1,	1,	79.6500,	2]).reshape(1,-1))

array([0])