# XGBoost For Regression

---

Extreme Gradient Boosting (XGBoost) provides an efficient and effective implementation of the gradient boosting algorithm




Regression predictive modeling problems involve predicting a numerical value such as a dollar amount or a height. **XGBoost** can be used directly for **regression predictive modeling**

---

# 1. Extreme Gradient Boosting

---

**Gradient boosting** refers to a class of ensemble machine learning algorithms that can be used for classification or regression predictive modeling problems


Ensembles are constructed form decision tree models. These are added one at a time to the ensemble and fit to correct the prediction errors made by prior models. This is a type of ensemble machine learning model referred to as boosting


Models are fit using any arbitrary differentiable loss funciton and gradient descent optimization algorithm. This gives the technique its name "gradient boosting", as the loss gradient is minimized as the model is fit, much like a neural network


It is designed to be both computationally efficient (e.g., fast to execute) and highly effective


The two main reasons to use XGBoost are execution speed and model performance


XGBoost dominates structured or tabular datassets on classification and regression predictive modeling problems

---

In [1]:
import xgboost as xgb

In [2]:
print(xgb.__version__)

3.4.1

Create an XGBoost Regressoin model

In [3]:
from xgboost import XGBRegressor

In [4]:
# model = XGBRegressor()

Hyperparameters:

* **n_estimators**: the number of trees in the ensemble, often increased until no further improvements are seen
* **max_depth**: the maximum depth of each tree, often values are between 1 and 10
* **eta**: the learning rate used to weight each model, often set to small vlaues such as 0.3, 0.1, 0.01, or samller
* **subsample**: the number of samples (rows) used in each tree, set to a value between 0 and 1, often 1.0 to use all samples
* **colsample_bytree**: number of features (columns) used in each tree, set to a value between 0 and 1, often 1.0 to use all features

#### XGBoost Regression Example

Develop an XGBoost model for a standard regression predictive modeling - housing dataset

In [5]:
# Load the dataset and show first five samples
import pandas as pd
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.csv'
df = pd.read_csv(url, header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [6]:
# Shape of the dataset
df.shape

(506, 14)

In [7]:
# Information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    int64
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    int64
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
 13  13      506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [8]:
# Check if there is any missing vlaue
df.isnull().sum().sum()/df.size * 100

np.float64(0.0)

In [9]:
# Check if there is any duplicate sample
df.duplicated().sum()

np.int64(0)

In [10]:
# Statistical Summary of the dataset
df.describe().T

,count,mean,std,min,25%,50%,75%,max
0,506.0,3.613524,8.601545,0.00632,0.082045,0.25651,3.677083,88.9762
1,506.0,11.363636,23.322453,0.00000,0.000000,0.00000,12.500000,100.0000
2,506.0,11.136779,6.860353,0.46000,5.190000,9.69000,18.100000,27.7400
3,506.0,0.069170,0.253994,0.00000,0.000000,0.00000,0.000000,1.0000
4,506.0,0.554695,0.115878,0.38500,0.449000,0.53800,0.624000,0.8710
5,506.0,6.284634,0.702617,3.56100,5.885500,6.20850,6.623500,8.7800
6,506.0,68.574901,28.148861,2.90000,45.025000,77.50000,94.075000,100.0000
7,506.0,3.795043,2.105710,1.12960,2.100175,3.20745,5.188425,12.1265
8,506.0,9.549407,8.707259,1.00000,4.000000,5.00000,24.000000,24.0000
9,506.0,408.237154,168.537116,187.00000,279.000000,330.00000,666.000000,711.0000
10,506.0,18.455534,2.164946,12.60000,17.400000,19.05000,20.200000,22.0000
11,506.0,356.674032,91.294864,0.32000,375.377500,391.44000,396.225000,396.9000
12,506.0,12.653063,7.141062,1.73000,6.950000,11.36000,16.955000,37.9700
13,506.0,22.532806,9.197104,5.00000,17.025000,21.20000,25.000000,50.0000

In [11]:
# Split the data into input and output features
X,y = df.iloc[:,:-1], df.iloc[:,-1]

In [12]:
X.shape, y.shape

((506, 13), (506,))

In [13]:
# define the model
model = XGBRegressor()

In [14]:
# Define model evaluation method
from sklearn.model_selection import cross_val_score, RepeatedKFold

cv = RepeatedKFold(
    n_splits = 10,
    n_repeats = 3,
    random_state = 1
)

# Evaluate model
scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring = 'neg_mean_absolute_error',
    n_jobs = -1
)

In [15]:
scores = abs(scores)
print(f"MAE: {scores.mean():.3f}")
print(f"STD: {scores.std():.3f}")

MAE: 2.156
STD: 0.334

In [16]:
model = XGBRegressor(
    n_estimators = 1000,
    max_depth = 3,
    eta = 0.01,
    subsample = 0.7,
    colsample_bytree = 0.8
)
model.fit(X,y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eta=0.01, eval_metric=None,
             feature_types=None, feature_weights=None, gamma=None,
             grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None, ...)

In [17]:
import numpy as np

new_data = np.array([0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30,396.90,4.98]).reshape(-1,13)

In [18]:
new_data.shape

(1, 13)

In [19]:
yhat = model.predict(new_data)
print(f"Predicted: {yhat[0]:.3f}")

Predicted: 25.324