In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Define dataset
from sklearn.datasets import make_classification
X,y = make_classification(
    n_samples=1000,
    n_features = 10,
    n_informative = 5,
    n_redundant = 5,
    random_state = 1
)

In [4]:
# Evaluate model
model = XGBClassifier()
cv = RepeatedStratifiedKFold(
    n_splits = 10,
    n_repeats = 3,
    random_state = 1
)

In [5]:
n_scores = cross_val_score(
    model,
    X,
    y,
    cv = cv,
    n_jobs = -1,
    error_score = 'raise'
)

In [7]:
print(f"Accuracy: {np.mean(n_scores):.3f}")
print(f"Standard Deviation: {np.std(n_scores):.3f}")

Accuracy: 0.933
Standard Deviation: 0.026

In [9]:
model = XGBClassifier()
model.fit(X,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [10]:
# Prediction
yhat = model.predict(np.array([2.56999479, -0.13019997, 3.16075093, -4.35936352, -1.61271951, -1.39352057, -2.48924933, -1.93094078, 3.26130366, 2.05692145]).reshape(1,-1))
print(f"Prediction: {yhat[0]:.3f}")

Prediction: 1.000

Iris Dataset

In [17]:
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns = data.feature_names)
df['species'] = data.target
df.sample(5)

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
9                  4.9               3.1  ...               0.1        0
117                7.7               3.8  ...               2.2        2
120                6.9               3.2  ...               2.3        2
60                 5.0               2.0  ...               1.0        1
116                6.5               3.0  ...               1.8        2

[5 rows x 5 columns]

In [18]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = ['species'])
y = df.species
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [20]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
yhat = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, yhat):.3f}")

Accuracy: 0.933

In [23]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
91                 6.1               3.0                4.6               1.4
135                7.7               3.0                6.1               2.3
69                 5.6               2.5                3.9               1.1
128                6.4               2.8                5.6               2.1
114                5.8               2.8                5.1               2.4

In [25]:
y_train.head()

91     1
135    2
69     1
128    2
114    2
Name: species, dtype: int64

In [27]:
model.predict(np.array([5.8,	2.8,	5.1,	2.4]).reshape(1, -1))

array([2])

In [32]:
model.predict(np.array([1.8,	6.8,	7.1,	2.4]).reshape(1, -1))

array([2])